version: '3.4'

services:
  angularapp:
    image: angularapp
    build:
      context: User
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4201:4201
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
